server:
  port: 8000

spring:
  application:
    name: spring-cloud-gateway
  # 是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。
  # 默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/api/book/**
# 指定注册中心的地址，以便使用服务发现功能
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

logging:
  level:
    org.springframework.cloud.gateway: debug

