server:
  port: 8000

# 指定注册中心的地址，启用服务发现功能
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

spring:
  application:
    name: spring-cloud-gateway
  # 是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。
  # 默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        # 图书服务
      - id: book-service
        uri: lb://book-service
        filters:
        - RequestTime
        predicates:
        - Path=/api/book/**
        # 图书馆服务
      - id: library-service
        uri: lb://library-service
        predicates:
        - Path=/api/library/**

logging:
  level:
    org.springframework.cloud.gateway: debug

